let content = [
  // 1. Pad Thai (آسيوي، متوسط)
  {
    num: 4.9,
    reviews: "(250 reviews)",
    img: "./images/photo1.jpg ",
    level: "Intermediate",
    cuisine: "Asian",
    title: "Pad Thai",
    description: "Popular Thai stir-fried noodles with shrimp and peanuts.",
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    ingred: [
      "200g rice noodles",
      "150g shrimp",
      "2 eggs",
      "3 tbsp tamarind sauce",
      "2 tbsp soy sauce",
      "1 tbsp fish sauce",
      "1 garlic clove, minced",
      "1/2 cup bean sprouts",
      "Crushed peanuts",
    ],
    instruc: [
      "Soak noodles in hot water for 10 minutes, drain.",
      "Stir-fry shrimp and garlic until cooked. Push to one side.",
      "Scramble eggs, then mix with shrimp.",
      "Add noodles and sauces (tamarind, soy, fish), stir well.",
      "Add bean sprouts and toss briefly. Cook for 2 minutes.",
      "Serve immediately, garnished with crushed peanuts.",
    ],
    Calories: "520 kcal",
    Protein: "36g",
    Carbohydrates: "54g",
    Fat: "18g",
    Fiber: "3g",
    Sodium: "620mg",
    tips: [
      "Use fresh tamarind paste for the best authentic flavor.",
      "Don't overcook the noodles, they should still be slightly firm.",
      "A hot wok is essential for a good Pad Thai stir-fry.",
      "Garnish with a lime wedge for extra zest.",
    ],
  },
  // 2. Classic Beef Burger (أمريكي، سهل)
  {
    num: 4.7,
    reviews: "(180 reviews)",
    img: "./images/photo2.jpg ",
    level: "Easy",
    cuisine: "American",
    title: "Classic Beef Burger",
    description: "Juicy beef patty served on a soft bun with fresh toppings.",
    prepTime: 25,
    cookTime: 20,
    servings: 3,
    ingred: [
      "500g ground beef",
      "3 burger buns",
      "Salt and black pepper",
      "1 tbsp oil",
      "3 slices cheese",
      "Lettuce, tomato, onion",
      "Ketchup and mustard",
    ],
    instruc: [
      "Season ground beef with salt and pepper, form 3 patties.",
      "Heat oil in a skillet or grill pan.",
      "Cook patties for 4-5 minutes per side for medium.",
      "Add cheese slice to each patty during the last minute of cooking.",
      "Toast the buns lightly.",
      "Assemble the burger with desired toppings and condiments.",
    ],
    Calories: "450 kcal",
    Protein: "30g",
    Carbohydrates: "35g",
    Fat: "22g",
    Fiber: "2g",
    Sodium: "550mg",
    tips: [
      "Don't overmix the meat to keep the patty tender.",
      "Press a small dimple in the center of the patty to prevent bulging.",
      "Use high-quality ground beef (80/20 mix) for best flavor.",
      "Serve with crispy fries for a complete meal.",
    ],
  },
  // 3. Quick Tomato Pasta (إيطالي، سهل)
  {
    num: 4.8,
    reviews: "(320 reviews)",
    img: "./images/photo3.jpg ",
    level: "Easy",
    cuisine: "Italian",
    title: "Quick Tomato Pasta",
    description:
      "Simple, flavorful spaghetti with fresh tomato and basil sauce.",
    prepTime: 15,
    cookTime: 10,
    servings: 2,
    ingred: [
      "200g spaghetti",
      "400g canned crushed tomatoes",
      "2 cloves garlic, minced",
      "2 tbsp olive oil",
      "1/2 tsp dried oregano",
      "Fresh basil leaves",
      "Salt and pepper",
      "Parmesan cheese (optional)",
    ],
    instruc: [
      "Cook spaghetti according to package directions.",
      "Heat olive oil in a saucepan, sauté garlic until fragrant.",
      "Add crushed tomatoes and oregano. Simmer for 5 minutes.",
      "Drain pasta and add it to the sauce.",
      "Toss well to coat. Season with salt and pepper.",
      "Stir in fresh basil and serve immediately with Parmesan.",
    ],
    Calories: "380 kcal",
    Protein: "12g",
    Carbohydrates: "65g",
    Fat: "8g",
    Fiber: "6g",
    Sodium: "400mg",
    tips: [
      "Save a cup of pasta water before draining; use it to adjust sauce consistency.",
      "Use high-quality olive oil for a better flavor.",
      "If you prefer a sweeter sauce, add a pinch of sugar while simmering.",
      "Fresh basil is key for this simple dish.",
    ],
  },
  // 4. Chicken Biryani (هندي، متقدم)
  {
    num: 4.6,
    reviews: "(95 reviews)",
    img: "./images/photo4.jpg ",
    level: "Advanced",
    cuisine: "Indian",
    title: "Chicken Biryani",
    description: "Fragrant rice dish with spiced chicken and aromatic herbs.",
    prepTime: 30,
    cookTime: 25,
    servings: 5,
    ingred: [
      "500g chicken pieces",
      "2 cups Basmati rice",
      "1/2 cup plain yogurt",
      "2 onions, sliced",
      "Ginger-garlic paste",
      "Biryani spice mix",
      "Fresh cilantro and mint",
      "Saffron threads",
    ],
    instruc: [
      "Marinate chicken in yogurt, ginger-garlic paste, and spices for 30 min.",
      "Soak Basmati rice for 30 minutes, then cook partially (70%).",
      "Fry onions until golden brown (birista).",
      "Layer the marinated chicken, rice, birista, and fresh herbs in a pot.",
      "Add saffron-infused milk on top.",
      "Cook (dum) on low heat for 20 minutes until rice is fully cooked.",
    ],
    Calories: "610 kcal",
    Protein: "45g",
    Carbohydrates: "70g",
    Fat: "19g",
    Fiber: "5g",
    Sodium: "750mg",
    tips: [
      "Do not stir the rice and chicken during the 'dum' cooking stage.",
      "Use a heavy-bottomed pot to prevent burning.",
      "Authentic biryani uses whole spices, not just powder.",
      "Serve with raita (yogurt dip) to balance the spice.",
    ],
  },
  // 5. Avocado Toast (عالمي، سهل)
  {
    num: 5.0,
    reviews: "(500 reviews)",
    img: "./images/photo5.jpg ",
    level: "Easy",
    cuisine: "Global",
    title: "Avocado Toast",
    description:
      "A quick and healthy breakfast or snack, seasoned to perfection.",
    prepTime: 10,
    cookTime: 8,
    servings: 1,
    ingred: [
      "1 slice whole-wheat bread",
      "1/2 ripe avocado",
      "Pinch of sea salt",
      "Pinch of red pepper flakes",
      "Lemon juice (optional)",
      "Everything bagel seasoning (optional)",
    ],
    instruc: [
      "Toast the bread slice until golden and crisp.",
      "In a small bowl, mash the avocado with a fork.",
      "Season the avocado with sea salt and red pepper flakes.",
      "Spread the seasoned avocado evenly over the toast.",
      "Drizzle with lemon juice if desired.",
      "Top with extra seasoning if using, and serve immediately.",
    ],
    Calories: "280 kcal",
    Protein: "8g",
    Carbohydrates: "30g",
    Fat: "15g",
    Fiber: "9g",
    Sodium: "300mg",
    tips: [
      "Make sure the avocado is perfectly ripe (soft but not mushy).",
      "Toast the bread well—it needs to hold the avocado mash.",
      "A drizzle of good quality balsamic glaze adds complexity.",
      "Adding a poached egg turns it into a full meal.",
    ],
  },
  // 6. French Onion Soup (فرنسي، متوسط)
  {
    num: 4.3,
    reviews: "(60 reviews)",
    img: "./images/photo6.jpg ",
    level: "Intermediate",
    cuisine: "French",
    title: "French Onion Soup",
    description:
      "Rich, deeply flavored beef broth with caramelized onions, topped with cheesy croutons.",
    prepTime: 40,
    cookTime: 35,
    servings: 6,
    ingred: [
      "4 large yellow onions, thinly sliced",
      "2 tbsp butter",
      "1 tsp sugar",
      "1/2 cup dry white wine",
      "6 cups beef broth",
      "1 baguette, sliced",
      "Gruyère cheese, shredded",
      "Salt and pepper",
    ],
    instruc: [
      "Melt butter in a large pot, add onions and sugar. Cook slowly until deeply caramelized (about 30 min).",
      "Pour in wine and scrape up any brown bits (deglaze).",
      "Add beef broth, bring to a simmer, and cook for 10 minutes.",
      "Season with salt and pepper.",
      "Ladle soup into oven-safe bowls, top with toasted baguette slices.",
      "Cover bread with Gruyère cheese and broil until the cheese is melted and bubbly.",
    ],
    Calories: "310 kcal",
    Protein: "18g",
    Carbohydrates: "25g",
    Fat: "14g",
    Fiber: "4g",
    Sodium: "800mg",
    tips: [
      "The key to this soup is slowly caramelizing the onions—do not rush this step!",
      "Use high-quality beef broth for maximum flavor depth.",
      "Authentic recipes use Gruyère, but Swiss or Mozzarella can be substituted.",
      "Make sure your bowls are oven-safe before broiling.",
    ],
  },
  // 7. Shrimp Scampi (إيطالي، سهل)
  {
    num: 4.4,
    reviews: "(120 reviews)",
    img: "./images/photo7.jpg ",
    level: "Easy",
    cuisine: "Italian",
    title: "Shrimp Scampi",
    description:
      "Shrimp sautéed in a garlic, butter, and white wine sauce, typically served over pasta.",
    prepTime: 12,
    cookTime: 18,
    servings: 3,
    ingred: [
      "400g large shrimp, peeled and deveined",
      "2 tbsp olive oil",
      "4 tbsp butter",
      "4 cloves garlic, minced",
      "1/4 cup dry white wine",
      "2 tbsp fresh lemon juice",
      "Fresh parsley, chopped",
      "Salt, pepper, and red pepper flakes",
    ],
    instruc: [
      "Cook pasta according to package directions (if serving over pasta).",
      "In a large skillet, heat olive oil and 2 tbsp butter. Sauté garlic until fragrant.",
      "Add shrimp, salt, pepper, and red pepper flakes. Cook until pink (about 2-3 min per side).",
      "Remove shrimp, set aside.",
      "Add white wine and lemon juice to the skillet, scraping up bits. Reduce slightly.",
      "Stir in remaining butter and parsley. Return shrimp to the pan and toss to coat.",
    ],
    Calories: "350 kcal",
    Protein: "35g",
    Carbohydrates: "5g",
    Fat: "20g",
    Fiber: "1g",
    Sodium: "450mg",
    tips: [
      "Don't overcook the shrimp, or they will become tough.",
      "Use good quality dry white wine (like Pinot Grigio or Sauvignon Blanc).",
      "Serve immediately over linguine or zucchini noodles.",
      "The butter should be added off the heat to make the sauce smooth and glossy.",
    ],
  },
  // 8. Tacos al Pastor (مكسيكي، متوسط)
  {
    num: 4.1,
    reviews: "(45 reviews)",
    img: "./images/photo8.jpg ",
    level: "Intermediate",
    cuisine: "Mexican",
    title: "Tacos al Pastor",
    description:
      "Marinated pork slices, grilled and served in small tortillas with pineapple.",
    prepTime: 22,
    cookTime: 12,
    servings: 4,
    ingred: [
      "500g pork shoulder, thinly sliced",
      "Adobo marinade (chili, achiote, spices)",
      "1/2 cup pineapple, diced",
      "1/4 onion, diced",
      "Cilantro, chopped",
      "Corn tortillas",
      "Lime wedges",
      "Oil for cooking",
    ],
    instruc: [
      "Marinate pork slices in Adobo marinade for at least 3 hours or overnight.",
      "Grill or pan-fry the pork until cooked through and slightly charred.",
      "Chop the cooked pork into small pieces.",
      "Warm the corn tortillas.",
      "Fill tortillas with pork, pineapple, onion, and cilantro.",
      "Serve immediately with lime wedges.",
    ],
    Calories: "410 kcal",
    Protein: "30g",
    Carbohydrates: "38g",
    Fat: "15g",
    Fiber: "4g",
    Sodium: "580mg",
    tips: [
      "The key flavor comes from the Adobo marinade; ensure it's rich in achiote and dried chilies.",
      "Slice the pork as thin as possible for the best texture.",
      "A splash of oil helps the pork char nicely on the grill.",
      "Serve with a spicy salsa verde for an extra kick.",
    ],
  },
  // 9. Greek Salad (يوناني، سهل)
  {
    num: 4.5,
    reviews: "(210 reviews)",
    img: "./images/photo9.jpg ",
    level: "Easy",
    cuisine: "Greek",
    title: "Classic Greek Salad (Horiatiki)",
    description:
      "Refreshing salad with tomatoes, cucumbers, olives, and a large slice of feta cheese.",
    prepTime: 18,
    cookTime: 20,
    servings: 2,
    ingred: [
      "2 large tomatoes, cut into wedges",
      "1 cucumber, sliced",
      "1/2 red onion, thinly sliced",
      "1/2 cup Kalamata olives",
      "1 block Feta cheese",
      "3 tbsp extra virgin olive oil",
      "1 tbsp red wine vinegar",
      "Pinch of dried oregano",
    ],
    instruc: [
      "Combine tomatoes, cucumber, red onion, and olives in a bowl.",
      "In a small bowl, whisk together olive oil, red wine vinegar, and oregano.",
      "Pour dressing over the vegetables and toss gently.",
      "Place the whole block of Feta cheese on top of the salad.",
      "Drizzle extra olive oil and sprinkle with oregano over the Feta.",
      "Serve immediately with crusty bread.",
    ],
    Calories: "330 kcal",
    Protein: "15g",
    Carbohydrates: "18g",
    Fat: "24g",
    Fiber: "5g",
    Sodium: "700mg",
    tips: [
      "Authentic Greek salad does NOT contain lettuce.",
      "Use high-quality Feta cheese, preferably from sheep's milk.",
      "Don't dress the salad until just before serving to keep the vegetables crisp.",
      "The red wine vinegar adds the necessary tanginess.",
    ],
  },
  // 10. Chocolate Lava Cake (فرنسي، متوسط)
  {
    num: 4.0,
    reviews: "(30 reviews)",
    img: "./images/photo10.jpg ",
    level: "Intermediate",
    cuisine: "French",
    title: "Molten Chocolate Lava Cake",
    description:
      "A rich chocolate cake with a gooey, molten center. Perfect dessert.",
    prepTime: 35,
    cookTime: 30,
    servings: 5,
    ingred: [
      "100g dark chocolate",
      "100g butter",
      "2 large eggs",
      "2 tbsp sugar",
      "1 tbsp flour",
      "Pinch of salt",
      "Vanilla ice cream (for serving)",
    ],
    instruc: [
      "Preheat oven to 220°C (425°F). Grease and flour ramekins.",
      "Melt chocolate and butter together until smooth.",
      "Whisk eggs, sugar, and salt until pale and fluffy.",
      "Gently fold the melted chocolate mixture into the egg mixture.",
      "Sift in the flour and fold until just combined.",
      "Pour batter into ramekins and bake for 12-14 minutes.",
    ],
    Calories: "390 kcal",
    Protein: "8g",
    Carbohydrates: "45g",
    Fat: "22g",
    Fiber: "2g",
    Sodium: "150mg",
    tips: [
      "Do not overbake! The edges should be set, and the center should still look soft.",
      "Use high-quality dark chocolate (70% cocoa or more) for the best flavor.",
      "The batter must be folded gently to keep air in the eggs.",
      "Serving with a scoop of vanilla ice cream creates a perfect contrast.",
    ],
  },
  // 11. Chicken Noodle Soup (أمريكي، سهل)
  {
    num: 4.9,
    reviews: "(400 reviews)",
    img: "./images/photo11.jpg ",
    level: "Easy",
    cuisine: "American",
    title: "Hearty Chicken Noodle Soup",
    description:
      "A comforting soup with tender chicken, vegetables, and egg noodles.",
    prepTime: 14,
    cookTime: 11,
    servings: 3,
    ingred: [
      "1 tbsp olive oil",
      "1 cup chopped carrots",
      "1 cup chopped celery",
      "1/2 cup chopped onion",
      "4 cups chicken broth",
      "1 cup cooked, shredded chicken",
      "1 cup egg noodles",
      "Salt and pepper to taste",
    ],
    instruc: [
      "Heat oil in a large pot, sauté carrots, celery, and onion until tender.",
      "Add chicken broth and bring to a boil.",
      "Add egg noodles and cook until al dente.",
      "Stir in the shredded chicken.",
      "Simmer for a few minutes to heat through.",
      "Season generously with salt and pepper before serving.",
    ],
    Calories: "210 kcal",
    Protein: "20g",
    Carbohydrates: "25g",
    Fat: "5g",
    Fiber: "3g",
    Sodium: "850mg",
    tips: [
      "Use low-sodium chicken broth to control the saltiness.",
      "For a rich flavor, use homemade chicken stock.",
      "Don't add the noodles until just before serving, or they will soak up all the broth.",
      "Add a bay leaf during the simmering for an earthy note.",
    ],
  },
  // 12. Lentil Curry (هندي/نباتي، متوسط)
  {
    num: 4.2,
    reviews: "(85 reviews)",
    img: "./images/photo12.jpg ",
    level: "Intermediate",
    cuisine: "Indian",
    title: "Red Lentil Curry (Dal)",
    description:
      "A spicy, vegetarian Indian stew made from red lentils and a blend of spices.",
    prepTime: 27,
    cookTime: 22,
    servings: 4,
    ingred: [
      "1 cup red lentils (masoor dal)",
      "4 cups water",
      "1 onion, chopped",
      "2 tomatoes, chopped",
      "Ginger-garlic paste",
      "1 tsp cumin powder",
      "1/2 tsp turmeric powder",
      "Fresh cilantro for garnish",
    ],
    instruc: [
      "Wash and soak lentils for 30 minutes, then cook with turmeric and water until soft.",
      "Sauté onion, ginger-garlic paste, and tomatoes in a separate pan.",
      "Add cumin powder and other spices to the sautéed vegetables.",
      "Mix the spice mixture into the cooked lentils.",
      "Simmer for 5-10 minutes to allow flavors to meld.",
      "Garnish with fresh cilantro and serve with rice or roti.",
    ],
    Calories: "380 kcal",
    Protein: "22g",
    Carbohydrates: "60g",
    Fat: "6g",
    Fiber: "15g",
    Sodium: "350mg",
    tips: [
      "Ensure the lentils are fully cooked and creamy, not gritty.",
      "The 'tadka' (tempering of spices in hot oil) added at the end elevates the flavor.",
      "Lentils absorb water quickly; add more if the consistency is too thick.",
      "Best served hot with freshly baked naan bread.",
    ],
  },
  // 13. Caprese Skewers (إيطالي، سهل)
  {
    num: 4.6,
    reviews: "(150 reviews)",
    img: "./images/photo13.jpg ",
    level: "Easy",
    cuisine: "Italian",
    title: "Caprese Salad Skewers",
    description:
      "Bite-sized appetizers featuring mozzarella, tomato, and basil.",
    prepTime: 16,
    cookTime: 14,
    servings: 2,
    ingred: [
      "1 pint cherry tomatoes",
      "1 block fresh mozzarella (small balls)",
      "Fresh basil leaves",
      "Balsamic glaze",
      "Olive oil",
      "Salt and pepper",
      "Wooden skewers",
    ],
    instruc: [
      "Thread one tomato, one basil leaf, and one mozzarella ball onto each skewer.",
      "Repeat the pattern until the skewer is full.",
      "Arrange the skewers on a platter.",
      "Drizzle with high-quality olive oil.",
      "Season lightly with salt and pepper.",
      "Finish with a generous drizzle of balsamic glaze.",
    ],
    Calories: "240 kcal",
    Protein: "12g",
    Carbohydrates: "10g",
    Fat: "18g",
    Fiber: "2g",
    Sodium: "200mg",
    tips: [
      "Use fresh, good quality mozzarella (bocconcini or ciliegine).",
      "The basil leaves should be fresh and vibrant green.",
      "Make the balsamic glaze thicker by reducing balsamic vinegar on the stove.",
      "Serve them chilled for the best refreshing taste.",
    ],
  },
  // 14. Shepherd's Pie (بريطاني، متقدم)
  {
    num: 3.9,
    reviews: "(20 reviews)",
    img: "./images/photo14.jpg ",
    level: "Advanced",
    cuisine: "British",
    title: "Traditional Shepherd's Pie",
    description:
      "A hearty layer of minced lamb (or beef) stew topped with creamy mashed potatoes.",
    prepTime: 45,
    cookTime: 40,
    servings: 6,
    ingred: [
      "1 kg potatoes, for mash",
      "500g ground lamb (or beef)",
      "1 onion, chopped",
      "2 carrots, diced",
      "1 cup beef broth",
      "1 tbsp Worcestershire sauce",
      "Milk and butter for mash",
      "Salt and pepper",
    ],
    instruc: [
      "Boil potatoes until tender, then mash with milk and butter until creamy.",
      "Sauté onion and carrots in a pan.",
      "Add ground meat and cook until browned, drain excess fat.",
      "Stir in broth and Worcestershire sauce. Simmer until sauce is reduced and thickened.",
      "Transfer meat mixture to a baking dish.",
      "Top evenly with mashed potatoes, creating peaks with a fork.",
    ],
    Calories: "580 kcal",
    Protein: "40g",
    Carbohydrates: "45g",
    Fat: "30g",
    Fiber: "7g",
    Sodium: "650mg",
    tips: [
      "Use lamb for authentic Shepherd's Pie, or beef for Cottage Pie.",
      "Ensure the meat filling is thick, not watery, before adding the mash.",
      "Bake the pie until the potato topping is golden and crisp.",
      "A piping bag can be used for a neat potato topping.",
    ],
  },
  // 15. Banana Smoothie (عالمي، سهل)
  {
    num: 4.8,
    reviews: "(260 reviews)",
    img: "./images/photo15.jpg ",
    level: "Easy",
    cuisine: "Global",
    title: "Simple Banana Smoothie",
    description:
      "A quick and nutrient-dense blend, perfect for a pre- or post-workout boost.",
    prepTime: 13,
    cookTime: 9,
    servings: 1,
    ingred: [
      "1 frozen banana, chopped",
      "1/2 cup milk (dairy or non-dairy)",
      "1/4 cup plain yogurt",
      "1 tbsp honey or maple syrup",
      "Pinch of cinnamon",
      "Optional: 1 tbsp peanut butter",
    ],
    instruc: [
      "Place all ingredients (banana, milk, yogurt, sweetener, cinnamon) into a blender.",
      "Start blending on low speed, gradually increasing to high.",
      "Blend until the mixture is completely smooth and creamy.",
      "If too thick, add a little more milk; if too thin, add more frozen banana or ice.",
      "Pour into a glass.",
      "Serve immediately, topped with a sprinkle of cinnamon.",
    ],
    Calories: "290 kcal",
    Protein: "10g",
    Carbohydrates: "55g",
    Fat: "5g",
    Fiber: "6g",
    Sodium: "100mg",
    tips: [
      "Use **frozen** bananas for the best, coldest, and thickest smoothie texture.",
      "Add liquids first, then soft ingredients, and finally frozen items to the blender.",
      "For extra protein, add a scoop of protein powder.",
      "Adding a small handful of spinach (though it changes the color) is a great nutrient boost.",
    ],
  },
  // 16. Lemon Herb Roasted Chicken (فرنسي، متوسط)
  {
    num: 4.7,
    reviews: "(175 reviews)",
    img: "./images/photo16.jpg ",
    level: "Intermediate",
    cuisine: "French",
    title: "Lemon Herb Roasted Chicken",
    description:
      "Whole chicken roasted with lemon, garlic, and herbs until skin is crispy.",
    prepTime: 21,
    cookTime: 19,
    servings: 3,
    ingred: [
      "1 whole chicken (1.5 kg)",
      "1 large lemon, halved",
      "4 cloves garlic, smashed",
      "4 tbsp butter, softened",
      "Fresh rosemary and thyme",
      "Salt and black pepper",
      "1 onion, quartered",
    ],
    instruc: [
      "Preheat oven to 200°C (400°F).",
      "Pat the chicken dry with paper towels for crispy skin.",
      "Mix softened butter with herbs, salt, and pepper.",
      "Rub the herb butter all over the chicken, including under the skin.",
      "Stuff the chicken cavity with lemon halves, garlic, and onion.",
      "Roast for about 75-90 minutes, or until internal temperature reaches 74°C (165°F).",
    ],
    Calories: "380 kcal",
    Protein: "45g",
    Carbohydrates: "5g",
    Fat: "20g",
    Fiber: "1g",
    Sodium: "480mg",
    tips: [
      "Tying the legs together (trussing) helps the chicken cook more evenly.",
      "Basting is not necessary and can actually soften the skin. Just leave it alone!",
      "Let the chicken rest for 10-15 minutes after roasting to retain the juices.",
      "For the crispiest skin, ensure the chicken is totally dry before seasoning.",
    ],
  },
  // 17. Black Bean Soup (مكسيكي، سهل)
  {
    num: 4.4,
    reviews: "(110 reviews)",
    img: "./images/photo17.jpg ",
    level: "Easy",
    cuisine: "Mexican",
    title: "Hearty Black Bean Soup",
    description:
      "A wholesome and flavorful vegetarian soup, often served with sour cream and cilantro.",
    prepTime: 24,
    cookTime: 26,
    servings: 5,
    ingred: [
      "1 tbsp olive oil",
      "1 onion, chopped",
      "1 bell pepper, chopped",
      "2 cloves garlic, minced",
      "2 cans black beans, rinsed and drained",
      "4 cups vegetable broth",
      "1 tsp cumin",
      "Toppings: sour cream, cilantro, lime",
    ],
    instruc: [
      "Heat oil in a pot, sauté onion and bell pepper until soft.",
      "Add garlic and cumin, cook for 1 minute.",
      "Add black beans and vegetable broth. Bring to a boil, then simmer for 15 minutes.",
      "Use an immersion blender to blend half of the soup for thickness (optional).",
      "Simmer for another 5 minutes, adjusting seasoning.",
      "Serve hot with a dollop of sour cream, chopped cilantro, and lime wedges.",
    ],
    Calories: "220 kcal",
    Protein: "15g",
    Carbohydrates: "35g",
    Fat: "4g",
    Fiber: "12g",
    Sodium: "720mg",
    tips: [
      "Blending half the soup creates a creamy texture without adding cream.",
      "A dash of smoked paprika adds depth and smoky flavor.",
      "Soaking and cooking dry beans from scratch adds a richer taste than canned.",
      "Top with crushed tortilla chips for added crunch.",
    ],
  },
  // 18. Egg Fried Rice (آسيوي، سهل)
  {
    num: 4.3,
    reviews: "(70 reviews)",
    img: "./images/photo18.jpg ",
    level: "Easy",
    cuisine: "Asian",
    title: "Quick Egg Fried Rice",
    description:
      "A classic side dish using day-old rice, scrambled eggs, and vegetables.",
    prepTime: 32,
    cookTime: 28,
    servings: 4,
    ingred: [
      "3 cups cooked, cold white rice",
      "2 tbsp oil",
      "2 eggs, scrambled",
      "1/2 cup peas and carrots (frozen)",
      "2 tbsp soy sauce",
      "1 tbsp oyster sauce (optional)",
      "1 tsp sesame oil",
      "Chopped scallions for garnish",
    ],
    instruc: [
      "Heat oil in a wok or large skillet over high heat.",
      "Add peas and carrots, stir-fry for 2 minutes.",
      "Add the cold rice, breaking up any clumps. Stir-fry for 3-5 minutes.",
      "Push the rice to one side, add the scrambled eggs to the empty space and cook slightly.",
      "Toss the rice, eggs, soy sauce, and oyster sauce together until well mixed.",
      "Stir in sesame oil and garnish with scallions.",
    ],
    Calories: "310 kcal",
    Protein: "10g",
    Carbohydrates: "50g",
    Fat: "8g",
    Fiber: "2g",
    Sodium: "600mg",
    tips: [
      "The most important rule: use **day-old, cold rice**; fresh rice will clump and be mushy.",
      "Use high heat and a well-seasoned wok for authentic results.",
      "Add a drop of white pepper for an authentic flavor.",
      "Toss, don't stir, the rice to keep the grains separate.",
    ],
  },
  // 19. Grilled Salmon with Asparagus (عالمي، سهل)
  {
    num: 4.6,
    reviews: "(190 reviews)",
    img: "./images/photo19.jpg ",
    level: "Easy",
    cuisine: "Global",
    title: "Grilled Salmon with Asparagus",
    description:
      "Healthy and flavorful salmon fillets grilled alongside fresh asparagus spears.",
    prepTime: 11,
    cookTime: 7,
    servings: 2,
    ingred: [
      "2 salmon fillets",
      "1 bunch asparagus, trimmed",
      "2 tbsp olive oil",
      "1 lemon, sliced",
      "1 tsp paprika",
      "Salt and pepper",
      "Garlic powder",
    ],
    instruc: [
      "Preheat grill to medium-high heat.",
      "Toss asparagus with 1 tbsp oil, salt, and pepper.",
      "Rub salmon fillets with remaining oil, salt, pepper, paprika, and garlic powder.",
      "Place salmon (skin side down) and asparagus on the grill.",
      "Grill salmon for 4-6 minutes, then flip and cook for 1-2 minutes more.",
      "Serve salmon topped with fresh lemon slices.",
    ],
    Calories: "430 kcal",
    Protein: "42g",
    Carbohydrates: "8g",
    Fat: "25g",
    Fiber: "4g",
    Sodium: "380mg",
    tips: [
      "Oil the grill grates well to prevent the salmon skin from sticking.",
      "Cook until the internal temperature of the salmon reaches 63°C (145°F).",
      "A foil boat can be used on the grill for easier cleanup.",
      "A squeeze of fresh lemon juice brightens the flavor.",
    ],
  },
  // 20. Tiramisu (إيطالي، متقدم)
  {
    num: 5.0,
    reviews: "(520 reviews)",
    img: "./images/photo10.jpg ",
    level: "Advanced",
    cuisine: "Italian",
    title: "Authentic Italian Tiramisu",
    description:
      "Classic no-bake Italian dessert with coffee-soaked ladyfingers and creamy mascarpone.",
    prepTime: 17,
    cookTime: 12, // (وقت التجميع وليس الطهي)
    servings: 3,
    ingred: [
      "6 large egg yolks",
      "1/2 cup sugar",
      "500g Mascarpone cheese",
      "1 cup strong espresso coffee, cooled",
      "2 tbsp dark rum (optional)",
      "24 ladyfinger biscuits",
      "Unsweetened cocoa powder",
    ],
    instruc: [
      "Whisk egg yolks and sugar until pale, then gently beat in the Mascarpone cheese.",
      "Mix cooled espresso with rum (if using) in a shallow dish.",
      "Quickly dip each ladyfinger into the coffee mixture (do not over-soak).",
      "Arrange a layer of dipped ladyfingers in the bottom of a dish.",
      "Spread half of the mascarpone mixture over the ladyfingers.",
      "Repeat layers, finishing with the mascarpone. Dust heavily with cocoa powder and chill for at least 4 hours.",
    ],
    Calories: "480 kcal",
    Protein: "15g",
    Carbohydrates: "55g",
    Fat: "25g",
    Fiber: "1g",
    Sodium: "250mg",
    tips: [
      "The key is **not to over-soak** the ladyfingers; a quick dip on each side is enough.",
      "Always use high-quality, full-fat mascarpone cheese.",
      "The chilling time is crucial for the cake to set and for the flavors to fully meld.",
      "Use unsweetened cocoa powder for dusting to balance the sweetness.",
    ],
  },
];
